### ISSUE TITLE
Interact stops with Ctrl-C

### ISSUE THREAD

**Issue by DavidGamba** [ThomasRooney/gexpect#18]
How can I send Ctrl-C to the interactive session but not the host session?

**Comment by ThomasRooney** [comment]
This is wanted behaviour -- Ctrl-C sends a SIGINT to a running child process so that we can terminate unresponsive instances.

Look into signal trapping to collect SIGINT (something like https://stackoverflow.com/questions/11268943/golang-is-it-possible-to-capture-a-ctrlc-signal-and-run-a-cleanup-function-in will help), and pass it to the subprocess. The subprocess can be terminated via `process.Kill()`,
